### ISSUE TITLE
@rematch/loading can't mention the state.loading.effects.model exisitence

### ISSUE THREAD

**Issue by nianiaJR** [rematch/rematch#632] opened 2019-04-25 10:34 UTC
I'm using rematch with typescript. I have a problem about:
![image](https://user-images.githubusercontent.com/8124783/56729653-6210eb80-6788-11e9-8286-d9dfda9db443.png)
I have a task model, it has a effect method like 'asyncTaskList’，but the typescript can't resolve if the interface 'asyncTaskList' exists. How can I solve this, thank you.

**Comment by yqz0203** [comment] 2019-04-26 09:42
Duplicate of #562

**Comment by nianiaJR** [comment] 2019-04-26 10:21
@yqz0203 thx, but I think they are not the same problem, in the [#562](https://github.com/rematch/rematch/issues/562), there isn't a loading definination in the `state`, so he use the typescript declaration merging to solve this(I did this already). In my problem, I want `state.loading.effects` to recognize what interfaces it has (such as the 'task'). It just judged the effects as a `any` type.

**Comment by yqz0203** [comment] 2019-04-26 10:24
> @yqz0203 thx, but I think they are not the same problem, in the [#562](https://github.com/rematch/rematch/issues/562), there isn't a loading definination in the `state`, so he use the typescript declaration merging to solve this(I did this already). In my problem, I want `state.loading.effects` to recognize what interfaces it has (such as the 'task'). It just judged the effects as a `any` type.

You can try [my solution](https://github.com/rematch/rematch/issues/562#issuecomment-473804575), works well.

**Comment by nianiaJR** [comment] 2019-04-28 07:29
Ok, I got it. Thx.

**Closed** 2019-04-28 07:29 UTC
