### ISSUE TITLE
npm run test error

### ISSUE THREAD

**Issue by JiangWeixian** [rematch/rematch#646] opened 2019-07-10 05:31 UTC
when i checkout this repo, after

```bash
npm run test:ts:setup
npm run test:ts
```

but, i got errors
 
```bash
FAIL  test/typescript.test.js (5.422s)
  typings
    ✕ should compile and run "examples/ts/count" without error (4626ms)

  ● typings › should compile and run "examples/ts/count" without error

    expect(received).not.toThrow()

    Error name:    "Error"
    Error message: "Semantic: examples/ts/count/src/index.tsx (9, 12) Property '[Symbol.observable]' is missing in type 'RematchStore<typeof import(\"/Users/qidanta/Documents/webprojects/rematch/examples/ts/count/src/models/index\"), Action<any, any>>' but required in type 'Store<any, AnyAction>'."
```

**Comment by hardfist** [comment] 2019-09-18 12:42
caused by redux's bug, see https://github.com/reduxjs/redux/issues/3466  ,should be fixed by https://github.com/rematch/rematch/pull/649

**Closed** 2019-09-18 12:43 UTC
