### ISSUE TITLE
when a model is dynamic added, the loading plugin don't work in some browers that doesn't install Redux Tools

### ISSUE THREAD

**Issue by wxwqslsdsh** [rematch/rematch#849] opened 2020-12-22 02:09 UTC
**Describe the bug**
since i use store.model method to dynamic add a new model named `editModel`, then in my react components, i use `useSelector` to get some loading status in the `editModel` such as `loading.effects.editModel.query`, then i got an error: cannot read property 'query' of undefined

**Expected behavior**
`loading.effects.editModel.query` can get a value of boolean

**Comment by tianzhich** [comment] 2020-12-22 02:18
Can you create a [sandbox](https://codesandbox.io/)?

**Comment by wxwqslsdsh** [comment] 2020-12-22 07:39
https://codesandbox.io/s/rematch-loading-bug-fy5gx
first you click the button there to go to another route, and then click the button in the new page, you'll see the result

**Comment by tianzhich** [comment] 2020-12-22 07:57
Could you try our next version `2.0.0-next.8`. We might have fixed this.

**Comment by wxwqslsdsh** [comment] 2020-12-22 08:36
I tried the version `2.0.0-next.8` you suggested in the codesandbox above, but i got the same error as well

**Comment by semoal** [comment] 2020-12-23 07:58
Probably the addModel method should reload plugins store if there any, lets take a further look
Thanks for the issue

**Comment by tianzhich** [comment] 2020-12-23 12:41
The reason is loadable list page, if put the `store.addModel({ ...editModel, name: "editModel" });` in index page or app's root, plugin works.
`

**Comment by semoal** [comment] 2020-12-24 14:03
If you add the `store.addModel()` inside an `useEffect`, the issue is gone. Probably it's something related to `redux` or `redux-devtools` magic or `loadable`... we can't help too much there.

I recommend using React.lazy and Suspense instead of Loadable if you are just searching code-splitting :)

**Comment by tianzhich** [comment] 2020-12-25 01:12
> If you add the `store.addModel()` inside an `useEffect`, the issue is gone. 

The issue is not gone. Did you enter the list page initially? If you enter the index and then click into the list page the issue appears.

**Comment by semoal** [comment] 2020-12-25 13:02
```js
  const { count, loading } = useSelector(
    ({ editModel: { count }, loading }) => ({
      count,
      loading: loading.effects.editModel?.query
    })
  );
```

Just use optional chaining, the problem is that addModel methods are run at the same time that useSelector is returning the state, I don't know how to "resolve" this, we'll need like a magic Suspense like lazy does, but with Redux and i'm not so expert to do that.

If you use a console.log of the loading object inside `Edit.js` you will see that loading object changes several times, that's why the first run fails.

**Comment by wxwqslsdsh** [comment] 2020-12-28 01:39
-- loading: loading.effects.editModel?.query
Thanks for the comment. This way can adapt my problem. If this issue can be resolved by the package itself,that will be the best

**Comment by semoal** [comment] 2020-12-28 09:48
Yes we'll see if we can do it in once render. Meanwhile this solution should work

**Comment by tianzhich** [comment] 2021-01-12 10:34
I did some async tests to simulate but working properly:
```ts
test('loading.global should be 0 for normal dispatched action', async () => {
	const store = init<Models, ExtraModels>({
		models: { count },
		plugins: [loadingPlugin({ asNumber: true })],
	})

	store.dispatch.count.addOne()
	expect(store.getState().loading.global).toBe(0)

	await expect(
		(async () => {
			await delay(1000)
			store.addModel({
				name: 'app2',
				state: 'Hello, model 2',
				reducers: {},
			})
			// @ts-ignore
			return store.getState().loading.models.app2
		})()
	).resolves.toEqual(0)
})
```

I still not sure if it was related to rematch.  😕

**Comment by semoal** [comment] 2021-01-13 09:59
Absolutely not, looks like a React render tree order, so we can close this issue.

**Closed by semoal** 2021-01-13 09:59 UTC
Labels: bug, invalid
