### ISSUE TITLE
[discuss] the way of use dispatch  impact the loading plugin

### ISSUE THREAD

**Issue by zhangwilling** [rematch/rematch#594] opened 2018-12-26 18:06 UTC
here are ways of dispatch using  in effects: 

  1. dispatch({ type: 'count/incrementAsync', payload: 1 })

  2. dispatch.count.incrementAsync(1)

the first will not emit loading, but second is ok.

a little bit confusing.

**Comment by jackwilsdon** [comment] 2018-12-27 15:11
Duplicate of #588

**Closed by jackwilsdon** 2018-12-27 15:11 UTC
