### ISSUE TITLE
@rematch/loading breaks effects in @rematch/core

### ISSUE THREAD

**Issue by derrickbeining** [rematch/rematch#629] opened 2019-04-05 13:47 UTC
Hi 👋 , happy user of @rematch here.

After a wild goose chase last night trying to figure out why my models' `effects` were all returning `Promise<undefined>` when they clearly shouldn't, I discovered this morning that if I disabled `@rematch/loading`, then my `effects` resume returning `Promise` for the expected value.

I took a peak at `@rematch/loading` on npm and discovered that there were two releases "a month ago", one for `v1.1.3` and then another one for `v.0.5.1`, so now the latest on npm is the latter.

In light of that, I `npm install --save @rematch/loading@1.1.3` and now the loading plugin doesn't hijack the return value of `effects`.

It appears the fix for this issue is simply to redeploy `@rematch/loading@1.1.3` to npm.

**Comment by jackwilsdon** [comment] 2019-04-05 13:54
It appears that the problem is in fact that `0.5.1` is tagged as `latest`, whilst `1.1.0` is still a `next` version (i.e. a "beta"). I'm not sure if this is the case anymore, and if so then the existing `1.1.3` should just be tagged as `latest` without another deployment.

Tagging @ShMcK because I don't know who else has NPM publishing rights.

**Comment by mauleb** [comment] 2019-04-10 16:09
Effects are broken for me with a react native project using core@1.1.0 and loading@1.1.3. Getting undefined like everyone else has been.

**Comment by mathew3** [comment] 2019-04-14 21:29
I was getting `undefined` from all effects with `"@rematch/loading": "0.5.1"` 

fixed by @derrickbeining advice

```
"@rematch/core": "^1.1.0",
"@rematch/loading": "1.1.3",
```

**Comment by ShMcK** [comment] 2019-04-14 22:49
I've updated @rematch/loading to have the npm tag for latest.

**Comment by semoal** [comment] 2019-04-25 08:59
Looks the issue is fixed with @ShMcK retag!

**Closed by semoal** 2019-04-25 08:59 UTC
